matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd python
      script:
        - python3 -m unittest discover -v --pattern *_tests.py

    - language: java
      jdk: openjdk8
      dist: trusty
      before_script:
        - cd java

    - language: cpp
      compiler: gcc
      dist: trusty
      before_script:
        - cd cpp
      script:
        - ./build.sh
