matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install coverage
        - pip install codecov

      before_script:
        - cd python
      script:
        - coverage run --source=src -m unittest discover -v --pattern *_tests.py
      after_success:
        - codecov

    - language: java
      jdk: openjdk8
      dist: trusty
      before_script:
        - cd java
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: cpp
      compiler: gcc
      dist: trusty
      before_script:
        - cd cpp
      script:
        - ./build.sh

