matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd python
      script:
        - python3 -m unittest discover -v --pattern *_tests.py

    - language: java
      jdk: openjdk8
      dist: trusty
      before_install:
        - cd java

    - language: cpp
      compiler: gcc
      dist: trusty
      script:
        - mkdir -p cpp/build
        - cd cpp/build
        - cmake ..
        - cmake --build .
        - ./training_test
      
